### ISSUE TITLE
Alert during startup on Win SRV 2008R2

### ISSUE THREAD

**Issue by balzercomp** [miyako/4d-component-7-zip#1]
When using the 7zip component, I get an error with the command "Application Type" during the DB startup of a 4D server 14.4 db on win srv 2008 r2. The error disappears as soon as the component is removed. I cannot see any reason for this behavior.

**Comment by miyako** [comment]
did you TRACE the code? are you calling the component from your server startup method?
because, the component doesn't use "On Host Database Event"


宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by balzercomp** [comment]
No, I didn't. But that's my problem. I cannot see any reason for the behaviour. It simply appears when I add the component and disappears when I remove it. There is only one call when I zip some files. And, of course, this is not in the startup methode.

**Comment by miyako** [comment]
wild guess, may be there is a rogue ``.4DIndy`` file that needs to be recreated (trashed)?

**Comment by balzercomp** [comment]
I’ll give it a try, If I can reproduce it with a different DB I will send it.

Cheers 

Gerald

**Comment by balzercomp** [comment]
Hi Keisuke,

sorry for letting you wait such long. Included is an empty db (only one methode with just some comment) that shows the behaviour, It simply has the original 7Z component. Openning this DB on Win 7, Win Srv 2008re or Win Srv 2012 results in an error with missing „Application Type“. This happens with 4D 14.4, 14.5 and 15.x. The error pops up on the server, single user and each windows client.



My question is simple: what can I do?

Here*s the link to the db on my dropbox: https://www.dropbox.com/s/i449i19sxljzr30/test_server.4dbase.zip?dl=0

Thanks for your help

Gerald

**Comment by miyako** [comment]
problem is not reproducible, must be specific to your system.

**Comment by miyako** [comment]
wild guess, maybe the database lang, component lang, 4D lang, or OS lang is the problem?
