### ISSUE TITLE
Error 126

### ISSUE THREAD

**Issue by vwayvatech** [miyako/4d-component-7-zip#2]
![error_126](https://user-images.githubusercontent.com/23177235/38884557-d78b07ae-4224-11e8-8b03-b18a1838e4a8.png)

A customer is using your component in v16R6 but is running into this issue in Windows "Error 126".  Originally, the DB is in v14 and I was able to open it and upgrade to v16R6 but when you close the application and open it again, I see the Error 126.  Have any suggestions?  Thanks in advance.

**Comment by miyako** [comment]
the component puts the 7z executable in a plugins folder, **which is not normal**. perhaps you could move it somewhere else, like Resources and modify the method that calls it accordingly.
