### ISSUE TITLE
Remove PLATFORM PROPERTIES call

### ISSUE THREAD

**Issue by WayneStewart** [miyako/4d-component-7-zip#3]
Hi Keisuke,

These methods need revision to remove obsolete 4D command

Thanks,

Wayne

[LEP_Escape.txt](https://github.com/miyako/4d-component-7-zip/files/6979427/LEP_Escape.txt)
[LEP_Escape_path.txt](https://github.com/miyako/4d-component-7-zip/files/6979428/LEP_Escape_path.txt)

**Comment by miyako** [comment]
I don't think there is any value in removing [_o_PLATFORM PROPERTIES](https://doc.4d.com/4Dv17/4D/17.5/o-PLATFORM-PROPERTIES.301-5256642.en.html). I won't use it in new development, for sure, but the command is thread safe and works just fine. also, the way to update a public repository is to create a pull request, there is no need to post txt files.

but I have updated the methods manually, for closure.
